### ISSUE TITLE
KNOWN ISSUE: My lab passes the tests regardless of which files have the Dog and Person classes.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/instance-methods-lab-ruby#6]
This isn't too big of an issue, but I did find something interesting. The Rspec tests do not check for WHERE in the files the Dog and Person classes are defined; only WHETHER they are defined.

What this means is that the following situations will pass the tests:
1) The lib/dog.rb file contains the Person class, and the lib/person.rb file contains the Dog class.
2) The lib/dog.rb file contains both classes, while the lib/person.rb file is empty.
3) The lib/person.rb file contains both classes, while the lib/dog.rb file is empty.

My guess is that two Rspec files are needed: one that requires and tests lib/dog.rb, and one that requires and tests lib/person.rb. The goal, obviously, is to make sure that the Dog class is in lib/dog.rb and the Person class is in lib/person.rb.

Again, I know this isn't a major issue, but thank you for looking into this.

Sdcrouse

**Comment by Sdcrouse** [comment]
I should note that I encountered the exact same problem with the Object Attributes Lab and the Object Initialize Lab.

**Comment by drakeltheryuujin** [comment]
Hi @Sdcrouse,

I'm looking this issue. Unfortunately, it does not appear that breaking them into separate files and requiring the lib files in each does not resolve this issue. 

Thanks!

**Comment by morgvanny** [comment]
While I don't believe Ruby has a built in way to check where a particular _class_ is defined, there is a relatively easy way to check in which file a particular _method_ is located.

If we want to ensure the Dog class is in dog.rb we could do this:

`expect(Dog.new.method(:bark).source_location[0]).to include('lib/dog.rb')`

And for Person, this:

`expect(Person.new.method(:talk).source_location[0]).to include('lib/person.rb')`

However, that requires those classes to have those methods in order to pass, so it's really testing a bit more than just if the class is in the right place. I'm not sure if I like it, because it can make the tests a bit more confusing, but maybe it would be fine.

**Comment by sgharms** [comment]
We've moved this to known issue status and we'll re-assess how we're instrumenting these labs as part of a more generalized upgrade to the Ruby module. Thanks for input.

**Comment by Sdcrouse** [comment]
You're welcome! Thanks for looking into that issue, everyone!

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#7.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team

**Comment by maxwellbenton** [comment]
Hey @Sdcrouse,

Just following up on this issue - we've added a note specifically calling this out in this lab and encouraging the proper organization of classes and files. This issue impacts many of our labs, as technically, all the files being tested in a lab are loaded it up prior to testing, so most solutions that involve multiple files can be solved by putting all the code in one file. In the more advanced labs, this is actually often necessary for the tests to function. Since these classes are loaded in the `spec_helper.rb` file, they will all be available from every spec file created that loads from the helper.

Since file organization isn't specifically a focus of any particular lab, and doesn't impact the other learning goals, we're going to leave the test structure as is. The key in this particular lab is that students know how to build classes and use instances. Adding the note to this lab, however, should help identify the way the tests work and the importance of separating classes into appropriately named files.
